# Generated by Django 4.1.5 on 2023-05-09 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_user_address_user_city_user_phone_user_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 9, 32, 3, 654306, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
