# Generated by Django 4.1.5 on 2023-05-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlist_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='image_url',
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
