# Generated by Django 4.1.5 on 2023-05-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_auctionlist_image_url_auctionlist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='image',
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=228, null=True),
        ),
    ]
